build_singularity_container:
  image: 
    name: quay.io/singularity/singularity:v3.10.4
    entrypoint: [""]

  stage: build

  tags:
    - linux
    - privileged

  artifacts:
    expire_in: 1 hrs
    paths:
      - Containers/rockylinux9-mpich.sif

  cache:
    key: 
      files: 
        - Containers/rockylinux9-mpich.def
    paths:
      - Containers

  script:
    - singularity build "Containers/rockylinux9-mpich.sif" "Containers/rockylinux9-mpich.def"


###############################################################################
run_hpc_cluster:
  image: python:latest

  stage: test

  needs: ["build_singularity_container"]

  before_script:
    - pip install hpc-rocket

  script:
    - hpc-rocket launch --watch rocket.yml
    - cat results/laplace.out

  artifacts:
    expire_in: 1 hrs
    paths:
      - results/



###############################################################################
regression_test:
  image: python:latest

  stage: test

  needs: ["run_hpc_cluster"]

  before_script:
    - pip install git+https://gitlab.com/dglaeser/fieldcompare

  script:
    - fieldcompare file results/TemperatureField.avs --reference reference_data/TemperatureField.avs