stages:
  - build
  - simulation
  - test
  - trigger
  - benchmark



###############################################################################
# 1. builds the singularity container using a docker container
# Needs a priviliged gitlab runner.
# Input: Containers/rockylinux9-mpich.def
# Output: Containers/rockylinux9-mpich.sif
###############################################################################
build_singularity_container_mpich:
  image: 
    name: quay.io/singularity/singularity:v3.10.4
    entrypoint: [""]

  stage: build

  tags:
    - linux
    - privileged

  artifacts:
    expire_in: 1 hrs
    paths:
      - Containers/rockylinux9-mpich.sif

  cache:
    key:
      files:
        - Containers/rockylinux9-mpich.def
    paths:
      - Containers/

  script:
    - ls -l Containers
    - singularity build "Containers/rockylinux9-mpich.sif" "Containers/rockylinux9-mpich.def"

###############################################################################
# 1. builds the singularity container using a docker container
# Needs a priviliged gitlab runner.
# Input: Containers/rockylinux9-mpich.def
# Output: Containers/rockylinux9-mpich.sif
###############################################################################
build_singularity_container_openmpi:
  image: 
    name: quay.io/singularity/singularity:v3.10.4
    entrypoint: [""]

  stage: build

  tags:
    - linux
    - privileged

  artifacts:
    expire_in: 1 hrs
    paths:
      - Containers/rockylinux9-openmpi.sif

  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - Containers/rockylinux9-openmpi.sif

  script:
    - singularity build "Containers/rockylinux9-openmpi.sif" "Containers/rockylinux9-openmpi.def"

###############################################################################
# 1. builds the singularity container using a docker container
# Needs a priviliged gitlab runner.
# Input: Containers/rockylinux9-mpich.def
# Output: Containers/rockylinux9-mpich.sif
###############################################################################
build_singularity_container_mpich_bind:
  image: 
    name: quay.io/singularity/singularity:v3.10.4
    entrypoint: [""]

  stage: build

  tags:
    - linux
    - privileged

  artifacts:
    expire_in: 1 hrs
    paths:
      - Containers/rockylinux9-mpich-bind.sif

  cache:
    key:
      files:
        - Containers/rockylinux9-mpich-bind.def
    paths:
      - Containers/

  script:
    - singularity build "Containers/rockylinux9-mpich-bind.sif" "Containers/rockylinux9-mpich-bind.def"

###############################################################################
# 2. runs the container on the hpc cluster using hpc-rocket
# rocket.yml used the configuration file rocket.yml, copies the defined data
# to the cluster, submits a slurm job and copies data back
# Output: result data located in results/
###############################################################################
run_hpc_cluster_mpich_bind:
  image: python:3.10

  stage: simulation

  needs: ["build_singularity_container_mpich_bind"]

  before_script:
    - pip install hpc-rocket==0.3.1

  script:
    - hpc-rocket launch --watch example/rocket-mpich-bind.yml
    - cat results/laplace.out

  artifacts:
    expire_in: 1 hrs
    paths:
      - results/


###############################################################################
# 3. runs a regression data using fieldcompare
# Fieldcompare compares the in the last job produced data from results/
# with a set of reference files located in reference_data/
###############################################################################
regression_test:
  image: python:3.10

  stage: test

  needs: ["run_hpc_cluster_mpich_bind"]

  before_script:
    - pip install "fieldcompare[all]"

  script:
    - fieldcompare file results/TemperatureField.avs reference_data/TemperatureField.avs


###############################################################################
# Manually trigger the benchmark child pipeline
###############################################################################
create_benchmark_ci:
  image: python:3.10
  stage: benchmark

  before_script:
    - pip install -r jobgeneration/requirements.txt

  script: 
    - python3 -m jobgeneration

  artifacts:
    expire_in: 1 week
    paths:
      - generated/
  when: manual
  needs: [build_singularity_container_mpich, build_singularity_container_openmpi]

trigger:benchmark:
  stage: benchmark
  needs:
    - create_benchmark_ci
  trigger:
    include:
      - artifact: generated/benchmark-gitlab-ci.yml
        job: create_benchmark_ci
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

