#!/bin/bash -l

#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --time=01:00:00
#SBATCH --job-name=Laplace2D-HighRes
#SBATCH --ntasks-per-node=4
#SBATCH --output=highres-test/laplace.out

date

cd highres-test
source common.sh

echo_slurm_parameters
load_modules

mkdir -p results

export MPI_DIR="/cluster/mpi/mpich"
srun --mpi=pmi2 singularity exec --bind "$MPI_DIR" ~/Containers/rockylinux9-mpich-bind.sif /build/bin/laplace 2 2 512 512