#!/bin/bash -l

#SBATCH --partition=teaching
#SBATCH --nodes=1
#SBATCH --time=00:10:00
#SBATCH --job-name=LaplMPI
#SBATCH --ntasks-per-node=4

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURM_TASKS_PER_NODE"=$SLURM_TASKS_PER_NODE
echo "working directory = "$SLURM_SUBMIT_DIR
echo ""

mpirun -np 4 ./build/bin/Laplace2D_mpi_blocking